language: php

php:
  - 7.1
  - 7.0

install:
  - composer install --prefer-source

before_script:
  - composer self-update
  - |
    if [ $TRAVIS_PHP_VERSION = '7.0' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - bin/phpunit -c phpunit.xml.dist --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.0' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi